app:
  root: "/path/to/root"
  endpoint: "/your_endpoint"

uvicorn:
  inf: "0.0.0.0"
  port: 8000
  log_level: "info"

telegram:
  db_path: "{ROOT}/telegram/database.db"
  token: "your_token_here"

keys:
  priv_key: "alerk_priv_key"
  pub_key: "alerk_pub_key"  # optional
  sign_key: "alerk_sigh_key"

smalk:
  - pub_key: "smalk1_key"
    code: "smalk1_code"
  - pub_key: "smalk2_key"
    code: "smalk2_code"
  - pub_key: "smalk3_key"
    code: "smalk3_code"
